apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-mkvr
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-mkvr
    app.kubernetes.io/part-of: tkrw-pr714-0075-0064-app
  name: devfile-sample-mkvr
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-mkvr
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-mkvr
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0064-tenant/tkrw-pr714-0075-0064-app/devfile-sample-mkvr@sha256:1665d0c59126a584d2f30a8134fde60ea74c9bbe60ebf3a82898653d3816d668
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
